packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  "@hono/node-server": ^2.0.1
  "@hono/vite-dev-server": ^0.26.0
  "@types/node": ^26.1.1
  "hono": ^4.12.16
  "htmx.org": ^2.0.10
  "vite": ^8.0.10
overrides:
  "@astrojs/check>typescript": "6.0.3"
  "@astrojs/ts-plugin>typescript": "6.0.3"
saveExact: true
preferOffline: true
engineStrict: true
allowBuilds:
  esbuild: true
  lightningcss-cli: true
  unrs-resolver: true
