export type Css = 
  | 'formCheckboxInput'
  | 'formErrorMessage'
  | 'formInputControl'
  | 'formInputGroup'
  | 'formInputIcon'
  | 'formLabel'
  | 'formLegendBefore'
  | 'formRadioInput'
  | 'formRadioSet'
  | 'formRadioSetInlineWrapper'
  | 'formRadioSetOptions'
  | 'formTextInput'
  | 'formTextareaInput'
  | 'iconClear'
  | 'layoutAfter'
  | 'layoutBefore'
  | 'layoutInline'
  | 'layoutStack'
  | 'layoutTop';
export type CssVariables = 
  | '--form-accent-color'
  | '--form-border-color'
  | '--form-brand-text-color'
  | '--form-error-color'
  | '--form-font-size-s'
  | '--form-input-background-active-color'
  | '--form-input-background-color'
  | '--form-input-background-disabled-color'
  | '--form-input-background-hover-color'
  | '--form-input-scale'
  | '--form-muted-text'
  | '--form-space-2xs'
  | '--form-space-3xs'
  | '--form-space-l'
  | '--form-space-m'
  | '--form-space-s'
  | '--form-space-xl'
  | '--form-space-xs';
export type CssDataAttributes = never;
declare const styles: Record<Css, string>;
export default styles;
