export type Css = 'bordered' | 'checkboxInput' | 'chevronIcon' | 'clearIcon' | 'comboboxContainer' | 'comboboxInput' | 'comboboxResultsPopover' | 'errorMessage' | 'fieldGroup' | 'icon' | 'iconOff' | 'iconOn' | 'infoIcon' | 'infoTooltipPopover' | 'inputContainer' | 'inputGroup' | 'isActive' | 'labelBefore' | 'labelTop' | 'listbox' | 'listboxGroup' | 'listboxGroupLabel' | 'listboxOption' | 'org' | 'orientationColumn' | 'orientationRow' | 'popoverDescription' | 'popoverTriggerBtn' | 'radioInput' | 'rangeContainer' | 'rangeInput' | 'rangeNumberInput' | 'searchIcon' | 'selectContainer' | 'selectInput' | 'textInput' | 'textareaContainer' | 'textareaInput' | 'toggleSwitch' | 'toolBtn' | 'w3';
export type CssVariables = '--input-background-active-color' | '--input-background-color' | '--input-background-disabled-color' | '--input-background-hover-color';
export type DataShowMarker = 'true';
export type CssDataAttributes = {
  'data-show-marker': DataShowMarker;
};
declare const styles: {
  'bordered': string;
  'checkboxInput': string;
  'chevronIcon': string;
  'clearIcon': string;
  'comboboxContainer': string;
  'comboboxInput': string;
  'comboboxResultsPopover': string;
  'errorMessage': string;
  'fieldGroup': string;
  'icon': string;
  'iconOff': string;
  'iconOn': string;
  'infoIcon': string;
  'infoTooltipPopover': string;
  'inputContainer': string;
  'inputGroup': string;
  'isActive': string;
  'labelBefore': string;
  'labelTop': string;
  'listbox': string;
  'listboxGroup': string;
  'listboxGroupLabel': string;
  'listboxOption': string;
  'org': string;
  'orientationColumn': string;
  'orientationRow': string;
  'popoverDescription': string;
  'popoverTriggerBtn': string;
  'radioInput': string;
  'rangeContainer': string;
  'rangeInput': string;
  'rangeNumberInput': string;
  'searchIcon': string;
  'selectContainer': string;
  'selectInput': string;
  'textInput': string;
  'textareaContainer': string;
  'textareaInput': string;
  'toggleSwitch': string;
  'toolBtn': string;
  'w3': string;
};
export default styles;
